// <auto-generated />
using System;
using Desafio_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio_API.Migrations.Atendimento
{
    [DbContext(typeof(AtendimentoContext))]
    [Migration("20220916033939_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio_API.Model.Atendimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DtAtendimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EsperaId")
                        .HasColumnType("integer");

                    b.Property<int>("Mesa")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EsperaId");

                    b.ToTable("Atendimento");
                });

            modelBuilder.Entity("Desafio_API.Model.Espera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DtEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StatusPainel")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Espera");
                });

            modelBuilder.Entity("Desafio_API.Model.Atendimento", b =>
                {
                    b.HasOne("Desafio_API.Model.Espera", "Espera")
                        .WithMany()
                        .HasForeignKey("EsperaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espera");
                });
#pragma warning restore 612, 618
        }
    }
}
