// <auto-generated />
using System;
using Desafio_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio_API.Migrations
{
    [DbContext(typeof(EsperaContext))]
    partial class EsperaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio_API.Model.Espera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DtEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StatusPainel")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Esperas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
